### ISSUE TITLE
[BUG] Convert XYZColor to RGBColor throw an StackOverflowException exception

### ISSUE THREAD

**Issue by hualiao** [tompazourek/Colourful#52] opened 2020-03-03 01:14 UTC
I use the latest version 2.0.3 in .NETFramework 4.7.2, when convert XYZColor to RGBColor throw an StackOverflowException exception. The exception message 'System.StackOverflowException was unhandled Message: An unhandled exception of type 'System.StackOverflowException' occurred in Colourful.dll'.

Test code:
```
                // arange
                var input = new XYZColor(0.96422, 1.00000, 0.82521);
                var converter = new ColourfulConverter { WhitePoint = Illuminants.D50, TargetRGBWorkingSpace = RGBWorkingSpaces.sRGB };

                // act
                var output = converter.ToRGB(input);
```

**Comment by tompazourek** [comment] 2020-03-03 07:19
Thanks for the report, there's likely some bug regarding this.

I had this same error reported earlier this week, but wasn't able to reproduce it on my machine.

**Would it be possible to list the stack at some point before it overflows?** It would point me in the right direction knowing which methods are repeated in it.

Also, if you aren't willing to wait until I find the time to issue a fix for this, contributions via PRs are welcome.

**Closed** 2020-03-04 20:15 UTC
Labels: bug

**Comment by tompazourek** [comment] 2020-03-04 20:22
Hi @hualiao. I finally figured the issue. It was only happening when using older compilers (that explained why I didn't see it on my machine or on the tests), and was caused by a maybe not completely legit usage of "dynamic" inside the convertors.

I have now rewritten this without dynamic. It should work as usual. I have pushed a 2.0.4 release with the fix (should appear on NuGet as soon as they index it).

In case the issue persists even on 2.0.4, feel free to reopen the issue.

**Comment by hualiao** [comment] 2020-03-05 01:13
I update to 2.0.4 there is not problem. Thank you.
