### ISSUE TITLE
How to draw Chromaticities(cie xy) diagram

### ISSUE THREAD

**Issue by Henxun** [tompazourek/Colourful#119] opened 2023-03-17 12:52 UTC

**Comment by tompazourek** [comment] 2023-03-17 13:31
This is probably a duplicate of #80

**Closed by tompazourek** 2023-03-17 13:31 UTC

**Comment by tompazourek** [comment] 2023-03-17 15:19
> hi，tommpourek How to calculate the boundaries of the horseshoe

I have never done that, so I don't know exactly. Sorry. I think this is related https://en.wikipedia.org/wiki/Planckian_locus.

This library is more about conversion between color spaces, it doesn't have all tools for colorimetry, unfortunately :(

**Comment by Henxun** [comment] 2023-03-18 09:59
> > hi，tommpourek How to calculate the boundaries of the horseshoe
> 
> I have never done that, so I don't know exactly. Sorry. I think this is related https://en.wikipedia.org/wiki/Planckian_locus.
> 
> This library is more about conversion between color spaces, it doesn't have all tools for colorimetry, unfortunately :(

thank you!i got no idea for this, it's so difficult for me
